### ISSUE TITLE
Add a Windows CI build

### ISSUE THREAD

**Issue by mattwynne** [cucumber/aruba#287]
We could use http://www.appveyor.com/

**Comment by dg-ratiodata** [comment]
Yes definitely. Thought about that too.

**Comment by dg-ratiodata** [comment]
Done. I used a modified version of rspec's appveyor configuration. Hope the build is fine. If there are too many `C`-rubygems it is likely to fail while installing the gems... Had that problem too. Today you can't build a project on appveyor include `rugged` (gitlib2 bindings for ruby).

**Comment by dg-ratiodata** [comment]
@mattwynne or @aslakhellesoy 

Can anyone of you create an "organisational" account on appveyor? Otherwise all builds run under the personal account of someone, like aruba on my personal account at https://ci.appveyor.com/project/dg-ratiodata/aruba for now.

Here's a full description of the process: http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

**Comment by mattwynne** [comment]
Hi Dennis.

It seems like the account name “cucumber” has already been taken by someone on AppVeyor. Best I can seem to get is “cucumberbdd”: https://ci.appveyor.com/project/cucumberbdd/aruba <https://ci.appveyor.com/project/cucumberbdd/aruba>

Hope that helps.

**Comment by dg-ratiodata** [comment]
Great. Can you send me the badge url? You can found that one in the settings I think. It's a rather "obscure" url containing a hash values.
