### ISSUE TITLE
Process output does not wait for process to end

### ISSUE THREAD

**Issue by fgarcia** [cucumber/aruba#307]
I've just realized that in Rspec these two styles are different:

Version 1:

    r = run 'myapp --list'
    expect(r).to have_output /Usage:/
    expect(r.exit_status).to eq 0

Version 2:

    r = run 'myapp --list'
    expect(r.output).to include 'Usage:'
    expect(r.exit_status).to eq 0

Version 2 fails both expectations because only the custom matcher `have_output` waits for the command to finish before returning a result. Even in Version 1 the exit status check would have failed without the waiting of `have_output`

Is this the expected behaviour?

**Comment by maxmeyer** [comment]
Yes. That's an expected behaviour. The "old" code had a similar behaviour and so has the "new" matcher-one.

1. `Command#output`, `Command#exit_status` etc. only make the data available (getters), they do not start actions

2. `Command#stop`, `Command#terminate` need to be run explicitly.

I suggest that you change your tests like this:

1. Use matchers everywhere

~~~ruby
command = run 'myapp --list'
expect(command).to have_output /Usage:/
expect(command).to have_exit_status 0
~~~

2. Explicitly stop command

~~~ruby
let(:command) { run 'myapp --list' }
before(:each) { command.stop }
expect(command.output).to match /Usage:/
expect(command.exit_status).to eq 0
~~~

**Comment by maxmeyer** [comment]
I updated my last comment. You should better use `stop_all_commands`. Using `#stop` on command requires the announcer as parameter - in master.
