### ISSUE TITLE
Can't make to work "When I run cli interactively" with running a test "in-proccess"

### ISSUE THREAD

**Issue by evmorov** [cucumber/aruba#317]
Hi!
My problem is that "in_process" doesn't work with "interactive".

I've already seen these examples: https://github.com/cucumber/aruba/blob/master/features/steps/commands/in_process.feature and https://github.com/cucumber/aruba/blob/master/features/commands/interactive.feature.

I've made a simple test project where you can see the problem https://github.com/evmorov/aruba_in_proccess_interactive. There are two scenarios. The first "Running ruby interactively" is your example that works (it defines the cli and the test inside itself) and the second "Running real cli interactively" is mine with which I have the problem. When you run `bundle exec cucumber` you see that the execution waits for input. However if you comment (in env.rb):
```ruby
Aruba.configure do |config|
  config.command_launcher = :in_process
  config.main_class = Problem::Runner
end
```
you can run "Running real cli interactively" test without any problem.

**Comment by dg-ratiodata** [comment]
I pushed some more examples to clarify the use of `InProcess`: https://github.com/cucumber/aruba/blob/master/features/steps/commands/in_process.feature#L302 (line 302ff). 

But having a look at your code: I think this can never work. Reading from `STDIN` blocks ruby from going on. But writing can only appear later, but this point is never reached, because ruby is blocked. I cannot see how this can be solved with in_process! Threads do not helper either at least if you really want to be in_process/in_thread.

@mattwynne Do you have an idea?

**Comment by evmorov** [comment]
@dg-ratiodata thanks!
