### ISSUE TITLE
Circular require warnings

### ISSUE THREAD

**Issue by peter-murach** [cucumber/aruba#339]
Running latest version `v0.12.0` with `aruba/rspec` causes a lot of aruba circular require warnings - there's few instances of that such as `aruba/platform` etc... I've managed to downgrade aruba to `v0.7.4` which doesn't have that problem, all versions above seem to show this issue.

**Comment by dg-ratiodata** [comment]
@peter-murach Thanks for reporting this, I only see two of them (running rspec). They're now fixed in master. They will be "part" of 0.13.0. Can you do me a favor and add the other files were you get warnings from to this issue?

Regarding the other warnings: Personally I disagree with `warning: private attribute?` and prefer to follow @skmetz advice in her [book](http://www.amazon.com/Practical-Object-Oriented-Design-Ruby/dp/0321721330/ref=sr_1_1?ie=UTF8&qid=1452152274&sr=8-1&keywords=sandi+metz) to prefer methods over instance variables.

**Comment by peter-murach** [comment]
It seems you have fixed them all, nice.

On the issue of warnings, to me Ruby questioning the principle of accessor method with private modifier is sound. Why would you want to do this when the meaning of `@` is meant for private access. Similarly I don't see this clashing with Sandi's reasoning for preferring methods, because if you follow it then you can always make the accessors protected. Still unavailable to outside world but happy to share with ancestors.

A wider point, I found running tests and seeing few lines of warnings before the actual test results were shown a bit discouraging. This effect is also annoying in IRB. This annoyance though not significant i believe it makes the user experience less optimal. In my experience, I feel that there is a fine balance between design principles and actual library usage. My intention in my own projects is to make the experience as smooth as possible. Just sharing my experience with fellow open source enthusiast!

**Comment by dg-ratiodata** [comment]
> Why would you want to do this when the meaning of @ is meant for private access. 

Yes, but if I decide to change the implementation, I need to replace all @var occurences with the new implementation. If used a var-method upfront, I only need change the implentation at one place and I'm done.

The idea of using `protected` might be a good balanced way to implement it. I'm going to think about that one. I'm going to track this in another issue.

Thanks for sharing your experience. I hope that both user and contributor experience will become better with 1.0.0. :-)
