### ISSUE TITLE
Running commands on Windows is broken

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#387]
## Summary

Running commands on windows seems to be broken. Have look at this [build](https://ci.appveyor.com/project/cucumberbdd/aruba/build/461/job/5u82fqffagc4f72o#L273). **Anyone using Ruby on Windows is welcome to help us fixing this.**

## Expected Behavior

Commands should be run on Windows.

## Current Behavior

Running commands fails on AppVeyor CI.

```
```
## Possible Solution

Fix code to run commands.

## Steps to Reproduce (for bugs)

See [CI Build](https://ci.appveyor.com/project/cucumberbdd/aruba/build/461/job/5u82fqffagc4f72o#L273)

## Your Environment

- Version used: latest
- Operating System and version: AppVeyor CI

**Comment by hferentschik** [comment]
For what I can tell, the problem lies in _Aruba:Processes:SpawnProcess_. In the start method we have:

    @process = ChildProcess.build(*[command_string.to_a, arguments].flatten)

_command_string_ is of type _Aruba:Platforms:WindowsCommandString_. Prior to calling _to_a_ on this command string, it looks for example like this (which is correct):

    C:\Windows\System32\cmd.exe /c "C:\Ruby200-x64\bin\bundle.bat"

After _to_a_ it is:
 
   ["C:WindowsSystem32cmd.exe", "/c", "C:Ruby200-x64binbundle.bat"]

Notice that the path separator '\' is gone. I think the problem is that _WindowsCommandString_ uses Ruby's _Shellwords.split_ to process the command line. AFAIU _Shellwords_ should/can only be used for bash. It won't work on Windows. In particular it seems to tread '\' as an escape character.

This leads then in the end to the error of "The system cannot find the file specified".

**Comment by hferentschik** [comment]
I tried to temporarily modify _WindowsCommandString.to_a_ to do something like `__getobj__.to_s.split(' ')` (probably to simplistic) and the command now actually executes. Unfortunately, a new exception is then thrown in _Aruba:Processes:SpawnProcess.read_. The problem is `File.read command_string.to_s`. I am not so familiar with the code base, but my guess is that Aruba tries to save the output of a command to a file. This fails here, since _WindowsCommandString_ actually modifies the command to add _cmd.exe_, something like _C:\Windows\System32\cmd.exe /c "C:\Ruby200-x64\bin\bundle.bat"_. Calling _to_s_ on this and passing it to _File.read_ will of course fail. Not sure whether there are more problems still. Hope it helps.

**Comment by hferentschik** [comment]
Another minor detail. [Here](https://github.com/cucumber/aruba/blob/master/lib/aruba/processes/spawn_process.rb#L86): 

    raise LaunchError, "It tried to start #{commandline}. " + e.message

the variable 'commandline' is used which is not defined, creating a misleading error. It should be _command_string_ instead.

**Comment by dg-ratiodata** [comment]
Great! Thanks for the hint. Can you help me and send a PR fixing it?

**Comment by hferentschik** [comment]
This might be helpful

* http://stackoverflow.com/questions/5636601/is-there-an-equivalent-to-the-ruby-shellwords-module-for-the-windows-shell
* https://github.com/larskanis/shellwords

Not sure whether it is worth introducing a new dependency, but if all that's needed is the _split_ functionality it could be taken from there!?

**Comment by dg-ratiodata** [comment]
> I am not so familiar with the code base, but my guess is that Aruba tries to save the output oof a command to a file. 

No problem, I can guide you.

> AFAIU Shellwords should/can only be used for bash

Ah. Ok. 

> Not sure whether it is worth introducing a new dependency, but if all that's needed is the split functionality it could be taken from there!?

I would prefer to take over the bits we need. The gem is MIT-licensed so we don't have a problem here.

> https://github.com/cucumber/aruba/issues/387#issuecomment-218690403

That was fixed for the Unix/Linux part already with https://github.com/cucumber/aruba/pull/357. So we forgot this bit.

> Calling to_s on this and passing it to File.read 

Mmmh... Sure. That's a problem. Do you have a good idea how to implement it in a nice way? I would like to see Windows and Unix CommandString to be implemented quite similar. Maybe just add a `#raw` method to CommandString?

> he problem is File.read command_string.to_s. I am not so familiar with the code base, but my guess is that Aruba tries to save the output of a command to a file.

Yes, it reads the script and output its for debugging purposes when the correct announcer is given. I think it was `announce-command-content`.

> Not sure whether there are more problems still. 

Maybe. The windows support is still quite "brittle".

**Comment by hferentschik** [comment]
> Great! Thanks for the hint. Can you help me and send a PR fixing it?

I cannot promise anything, but maybe I can give a quick try...

**Comment by dg-ratiodata** [comment]
Yay. That would be great.

**Comment by jpc2** [comment]
Rather than starting something new...and a bit long...

I'm a relative newbie with Ruby. I'm an Old FORTRAN Programmer (and other things OFP can stand for). I use FRUIT to build tests for FORTRAN and it is Ruby based so I've gotten a bit into Ruby. I'd really like to use cucumber and aruba on Windows but.... Here is what I've found so far.

First problem: Trying to setup a simple CLI program with GLI and the book 'Build Awesome Command-Line Applications in Ruby 2', I try to run the basic infrastructure setup by GLI with cucumber and I get:

-----

`
C:\Work\Awesome_Cmd_Line_Apps\TODO_pgm\todo>cucumber
@annotate
Feature: My bootstrapped app kinda works
  In order to get going on coding my awesome app
  I want to have aruba and cucumber setup
  So I don't have to do it myself

  Scenario: App just runs            # features/todo.feature:7
    When I get help for "todo"       # features/step_definitions/todo_steps.rb:1
      Command "todo" not found in PATH-variable "C:/Work/Awesome_Cmd_Line_Apps/TODO_pgm/todo/bin:C:/Work/Awesome_Cmd_Line_Apps/TODO_pgm/todo/exe:_U1_;C:\Rubies\Ruby22\b
in;_U2_;C:\Program Files\MATLAB\MATLAB Runtime\v85\runtime\win64;C:\ProgramData\............
(Aruba::LaunchError)
      ./features/step_definitions/todo_steps.rb:3:in `/^I get help for "([^"]*)"$/'
      features/todo.feature:8:in `When I get help for "todo"'
    Then the exit status should be 0 # aruba-0.14.2/lib/aruba/cucumber/command.rb:278

Failing Scenarios:
cucumber features/todo.feature:7 # Scenario: App just runs

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m0.449s
` 
After staring at the PATH for a bit I noticed that the separators are wrong. This "/todo/bin:C:/Work/Awesome" should be "/todo/bin;C:/Work/Awesome". Windows uses ';' to separate things in the PATH and other lists of directories - others use ':'. It appears that the 'standard' way of handling this is File::PATH_SEPARAROR. Mucking around in the aruba code I found three files, aruba/rspec.rb, cucumber/command.rb and cucumber/hooks.rb with lines like this:

`  prepend_environment_variable 'PATH', aruba.config.command_search_paths.join(':') + ':'
`

I changed them to look like this:
  prepend_environment_variable( 'PATH', aruba.config.command_search_paths.join(File::PATH_SEPARATOR) + File::PATH_SEPARATOR)

There are probably others for things like LIB and such.
Now when I run cucumber I get:

------
`
C:\Work\Awesome_Cmd_Line_Apps\TODO_pgm\todo>cucumber
@annotate
Feature: My bootstrapped app kinda works
  In order to get going on coding my awesome app
  I want to have aruba and cucumber setup
  So I don't have to do it myself

  Scenario: App just runs            # features/todo.feature:7
    When I get help for "todo"       # features/step_definitions/todo_steps.rb:1
      undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x2f7e610> (NameError)
      ./features/step_definitions/todo_steps.rb:3:in `/^I get help for "([^"]*)"$/'
      features/todo.feature:8:in `When I get help for "todo"'
    Then the exit status should be 0 # aruba-0.14.2/lib/aruba/cucumber/command.rb:278

Failing Scenarios:
cucumber features/todo.feature:7 # Scenario: App just runs

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m0.145s

C:\Work\Awesome_Cmd_Line_Apps\TODO_pgm\todo>

`
----------

Second problem: 
So I set up a new directory and initialize aruba. (Ruby  -- 2.2.5, aruba - 0.14.2)
I copy in the console.feature file from the features/getting_started directory in the installed Gem. It appears to be the simplest that actually tries to run something that is not generated. Doesn't run!

I run cucumber and get

-----
`Feature: Aruba Console

  Background:                     # features/console.feature:3
    Given a mocked home directory # aruba-0.14.2/lib/aruba/cucumber/environment.rb:1

  Scenario: Start console                     # features/console.feature:6
    Given I run `aruba console` interactively # aruba-0.14.2/lib/aruba/cucumber/command.rb:50
      undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x28f04b8> (NameError)
      features/console.feature:7:in `Given I run `aruba console` interactively'
    When I close the stdin stream             # aruba-0.14.2/lib/aruba/cucumber/command.rb:64
    Then the output should contain:           # aruba-0.14.2/lib/aruba/cucumber/command.rb:206
      """
      aruba:001:0>
      """
`
-----
I've chased it a bit but haven't found why 'cmd' is undefined. 

I'd be happy if the basic run commands worked. There are thing that might never work but it should be possible to make some of it work.

**Comment by thomthom** [comment]
Is there a previous version of aruba that worked on Windows?

**Comment by thomthom** [comment]
Like @jpc2 I am running into `undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x3df8750> (NameError)`.

Though, I'm not sure if that is the same issue the original poster was referring to?

**Comment by thomthom** [comment]
This pull request fixed the issue for me: https://github.com/cucumber/aruba/pull/422

**Comment by SteveDonie** [comment]
We are using Aruba 0.8.1 on Windows and Linux - we have had to make local
changes to the gem to get that to work though. We also use JRuby rather
than "Matz" Ruby because we are testing a java program and use the sequel
gem and JDBC database drivers.

Here is a snippet from the docs that we give to new developers and testers:

Right now, there is a bug in Aruba 0.8.1 on Windows that requires manually
editing one of the files in that gem.

using notepad++ or similar, edit
c:\Jrubyxxx\lib\ruby\gems\shared\geams\aruba-0.8.1\lib\aruba\processes\spawn_process.rb

On line 45, change the run! method.

def run!
 # rubocop:disable Metrics/LineLength
 my_path = environment['PATH'][0..-2] + File::PATH_SEPARATOR +
environment['Path']
 environment['PATH'] = my_path
 fail LaunchError, %(Command "#{command}" not found in PATH-variable
"#{my_path}".) unless which(command, my_path)
 # rubocop:enable Metrics/LineLength

 @process = ChildProcess.build(which(command, my_path), *arguments)
 @out = Tempfile.new("aruba-out")
 @err = Tempfile.new("aruba-err")
 @exit_status = nil
 @duplex = true

 before_run
