### ISSUE TITLE
User input not handled as expected

### ISSUE THREAD

**Issue by ngw** [cucumber/aruba#429]
I'm trying to test a basic GLI + HighLine project using Aruba, but for some reasons I'm not able to input anything into HighLine.
This is my feature:

    @announce-output
    Scenario: asks jornal_path configuration when missing
      Given a file named "config.yml" with:
      """
      :cobain:
      """
      When I run `bin/cobain -c config.yml bootstrap` interactively
      Then the output should contain "Where do you want to save your journal? (default ~/.journal)"
      And I type "~/.my_journal\n"
      And the output should contain "Cobain needs your email to lookup your GPG key"
      And I type "example@example.com"

What it does is initializing the script with an empty configuration file. The script then makes two questions, and HighLine.ask for an answer.
This is the script I'm testing:

    command :bootstrap do |c|
      c.action do |global_options, options, args|
        configuration = Cobain::Configuration.new(path: global_options[:config_path])
        global_options[:cli].say "#{global_options[:config_path]} loaded successfully"
        configuration.setup do |setting, question|
          configuration.send("#{setting}=", global_options[:cli].ask(question))
        end
      end
    end

global_options[:cli] is a HighLine instance, initialized with no arguments.
Here is the exception raised:

    And the output should contain "Cobain needs your email to lookup your GPG key"                # aruba-0.14.2/lib/aruba/cucumber/command.rb:159
      expected "config.yml loaded successfully\nWhere do you want to save your journal? (default ~/.journal)\nerror: SIGTERM" to string includes: "Cobain needs your email to lookup your GPG key"
      Diff:
      @@ -1,2 +1,4 @@
      -Cobain needs your email to lookup your GPG key
      +config.yml loaded successfully
      +Where do you want to save your journal? (default ~/.journal)
      +error: SIGTERM
       (RSpec::Expectations::ExpectationNotMetError)
      features/bootstrap.feature:24:in `And the output should contain "Cobain needs your email to lookup your GPG key"'
    And I type "example@example.com"                                                              # aruba-0.14.2/lib/aruba/cucumber/command.rb:59

Here is the @announce-output:

    <<-STDOUT
    config.yml loaded successfully
    Where do you want to save your journal? (default ~/.journal)

    STDOUT

    <<-STDERR
    error: SIGTERM

    STDERR

    <<-STDOUT
    config.yml loaded successfully
    Where do you want to save your journal? (default ~/.journal)

    STDOUT

    <<-STDERR
    error: SIGTERM

    STDERR

It seems to me that the input steps aren't working as I'd expect.
Bug, my mistake, how to fix this?

**Comment by maxmeyer** [comment]
@ngw I'm very sorry for the late reply. Since the command is stopped when you check its output (https://github.com/cucumber/aruba/blob/master/lib/aruba/matchers/command/have_output.rb#L22), you need to refactor your steps. Can you please verify this works?

~~~cucumber
@announce-output
Scenario: asks jornal_path configuration when missing
  Given a file named "config.yml" with:
  """
  :cobain:
  """
  And I run `bin/cobain -c config.yml bootstrap` interactively
  When I type "~/.my_journal\n"
  And I type "example@example.com"
  Then the output should contain "Where do you want to save your journal? (default ~/.journal)"
  And the output should contain "Cobain needs your email to lookup your GPG key"
~~~

BTW: I would also suggest to concentrate on those things you're "testing" in your "When"-step.
