### ISSUE TITLE
Make sure examples work on all supported platforms

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#453]
## Summary

Run the examples in our README for `cucumber`, `rspec` and  `minitest`.

@enkessler @mvz @olleolleolle Would you mind to run the examples found in our ["Getting started"-section](https://app.cucumber.pro/projects/aruba#your-first-tests-with-aruba) (Your First Tests with "aruba") on your machines? I modified them yesterday to show how to run and test commands with `aruba`. Do you think the examples are easy to understand for beginners?

## Expected Behavior

* [ ] The examples do work
* [ ] The examples are easy to understand
* The examples work on all platforms
  * [ ] Windows
  * [x] Linux
  * [x] Mac OS

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by olleolleolle** [comment]
I have now tried the examples, in the same repo checkout, after each other. It all works.

**Comment by maxmeyer** [comment]
@olleolleolle Thanks!

**Comment by mvz** [comment]
The examples all work on Linux, but I have three remarks:
* To ensure all dependencies are available from the start, I think you should add `bundle` to the start of the instructions, just after the clone.
* For some reason, `spec_helper.rb` already exists in that repo. Since you know this is the case, it would be more straightforward if the instructions just stated something like 'Add the following line to `spec_helper.rb`.
* The `$LOAD_PATH` line in the minitest example is not needed, since `-Ilib:test` is part of the command line.

**Comment by olleolleolle** [comment]
@mvz Re: dependencies, do you mean an addition to the README like https://github.com/cucumber/aruba/pull/454/files

**Comment by mvz** [comment]
@olleolleolle no, that pull request exactly fixes that point.

**Comment by maxmeyer** [comment]
@mvz Thanks for the feedback! I addressed your comments in #456.

**Comment by maxmeyer** [comment]
@mvz Would you mind joining the Cucumber Slack Room?

**Comment by maxmeyer** [comment]
https://cucumber.io/support

**Comment by maxmeyer** [comment]
BTW: I also updated our docs on RubyDocs.info as some of our users tried things they found in there.

**Comment by maxmeyer** [comment]
Shall be fixed for now. @mvz @olleolleolle Feel free to add more comments after closure.

**Comment by mvz** [comment]
> Would you mind joining the Cucumber Slack Room?

Request sent, thanks.
