### ISSUE TITLE
Reducing running platforms in Travis

### ISSUE THREAD

**Issue by junaruga** [cucumber/aruba#470]
## Summary

Considering supported platforms.

## Current Behavior

Right now aruba supports below platforms.
14 VMs (Virtual Machines) are running.
https://github.com/cucumber/aruba/blob/master/.travis.yml

Total running time is over than 1 hour.
https://travis-ci.org/cucumber/aruba/builds/258426774
> Ran for 1 hr 4 min 4 sec

I think that this situation is what we have to improve.

## Possible Solution

Cucumber supports below platforms.
https://github.com/cucumber/cucumber-ruby/blob/master/.travis.yml

I guess that we can remove below 7 cases?

```
  - 1.9.3
  - 2.0.0
  - jruby
  - jruby-20mode
  - jruby-21mode
```

```
    - rvm: jruby-9.1.12.0-20mode
      env: JRUBY_OPTS='--dev'
    - rvm: jruby-9.1.12.0-21mode
      env: JRUBY_OPTS='--dev'
```

## Context & Motivation

Reducing the number of VMs, saving the resource improves the total running time.
I have experienced similar situation in another project.
After reducing the number of VMs, the running time has been improved.

**Comment by junaruga** [comment]
As information, currently All the JRuby tests are error on Travis CI because of exceeding running time.
https://travis-ci.org/cucumber/aruba/builds/258937032

In my opinion, we should run only JRuby latest stable version 9.1.12.0 for JRuby tests as allow failure.
Then let's try to do tuning the tests.

**Comment by junaruga** [comment]
@maxmeyer how do you think of this topic?

**Comment by olleolleolle** [comment]
I support the removal of the "variant" builds for JRuby.

**Comment by maxmeyer** [comment]
## In General

@junaruga Yes, I would love to remove those outdated platforms. I like the way cucumber's `.travis.yml` is structured + they seem to test on MacOS. Let's take over their structure and add the "old" versions for now, but get rid of the `-mode`-variants.

~~~
  - 1.9.3
  - 2.0.0
  - jruby
~~~

Just for the records: We already using Travis' "Docker" infrastructure, so no real VMs are started for "aruba"'s builds.


## Remove all old versions:

Pros:
* Less work on our side
* Better response times on Travis

Cons:
* Cut support for those ruby versions in 1.0.0 would make it hard for projects like `rspec` to migrate to 1.0.0. RSpec for example even support Ruby 1.8.7.

Suggestion:
1. Get out 1.0.0 as early as possible - with all deprecated methods removed and all showstoppers (issues) closed
2. Make 1.0.0 the "still" version
3. Drop support of Rubies in `.travis.yml`
4. Release aruba 2.0.0

Thoughs:
* I see users of aruba as some kind of a customers
* Personally I want to make sure our users get the most out of "aruba"
* I don't want them to be forced to setup their own aruba
* I would love to see "rspec" using aruba for it's test suite as this is a "big" and well known project
* There are a lot projects which are using aruba 0.6.x due to upgrade issues. I would like to see those projects on board.
* Removing a supported Ruby version seems to be a breaking change thus the major version should be bumped.

@junaruga @olleolleolle @mvz What do you think?

## In the future

I think a policy for supported ruby versions would help. I see at least 5 options.

1. Only versions with support by the Ruby community according to the announcements on ruby-lang.org (https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)
2. Versions which are supported by the Cucumber-Ruby-project
3. Versions from 1. + Version(s) supported by major Linux distributions, e.g. RHEL
4. Versions selected from a pre-defined set of "big" projects (e.g. > 1000 stars on Github + Active in the Last year)
5. A mix of everything:
   * At least all versions by the Cucumber-Ruby-Project
   * At least the version(s) supported by major Linux Distributions
   * At  least all version from 1-3 big projects which do not cause that much pain on our side

**Comment by maxmeyer** [comment]
@junaruga For now this should be fixed by #476, but I'll leave this open as an reminder for 2.0.0

**Comment by junaruga** [comment]
Thank you for that!

**Comment by luke-hill** [comment]
I'll close this as fixed in my latest PR. This is something which is now distinctly more manageable (We use Xenial which runs faster, and have only 5*5 - 10 runs)
