### ISSUE TITLE
Current state of support for Windows

### ISSUE THREAD

**Issue by peagha** [cucumber/aruba#661]
## Summary

I read [this comment](https://github.com/cucumber/aruba/issues/521#issuecomment-370208294) and it raised the question about the current support for Windows:

> Windows support is rather experimental I'm afraid [...]

Does that apply to the Alpha version (1.0.0.pre.alpha.2) or to all the versions of the Gem?

## Possible Solution

If the Windows support is experimental we could inform this in the README 📜 

## Context & Motivation

I'm updating a book that uses Aruba and I would like to inform the readers if they may find bugs on Windows.

**Comment by mvz** [comment]
I have updated the README for the upcoming 1.0.0 release accordingly.

Support for Windows is tricky in general since at least Appveyor provides an almost-unix environment to run tests under. This means that available shell commands and their interface are different from what a user might encounter when running under, e.g., powershell or cmd.exe.

Pull requests and suggestions on how to improve the situation are welcome.
