### ISSUE TITLE
Test with multiple versions of Cucumber

### ISSUE THREAD

**Issue by mvz** [cucumber/aruba#729]
## Summary

Add some mechanism to test that Aruba still works with older versions of Cucumber that are officially supported.

## Expected Behavior

At least the combination of Aruba with Cucumber 2.4 is tested on TravisCI.

## Current Behavior

Tests are run with the latest Cucumber version supported on each Ruby version. This means versions older than Cucumber 4 are not tested.

## Possible Solution

Use the appraisal gem to test with different combinations of dependencies.

## Context & Motivation

I'd like to start using more modern ways of defining the steps, and also improve step wording, but I'm afraid I'll break support for older Cucumber versions.

**Comment by mvz** [comment]
The upcoming end of support for Ruby 2.5 may be a good time to increase the minimum versions of Aruba's dependencies. This should mitigate this problem as well.

**Comment by mvz** [comment]
Adding Appraisals may also help in testing with upcoming Cucumber releases. See #801.

**Comment by aurelien-reeves** [comment]
Short summary of the discussion we had in #801:

We keep dependency to `cucumber` bounded to the actual version of `cucumber`.

That is source of issues when working on releasing new versions of `cucumber`. We had a really hard time releasing `cucumber` version 6 because of circular dependencies: `cucumber` depends on `cucumber-wire` which depends on `aruba` which depends on `cucumber`.

It has been suggested to remove the upper-bound dependency version. That way, releasing new version of `cucumber` would be easier.

It has also been suggested to have some tests for `aruba` using `cucumber`'s master branch.

This is still an open discussion.
